### ISSUE TITLE
error on creating controller

### ISSUE THREAD

**Issue by danielmahon** [madhums/node-genem#3]
```
boilerplate > genem controller index
   create : ./app/controllers/
   create : ./app/controllers/index.js

/usr/local/share/npm/lib/node_modules/genem/node_modules/inflection/lib/inflection.js:173
        var ignore = ( this.indexOf( skip, str.toLowerCase()) > -1 );
                                               ^
TypeError: Cannot call method 'toLowerCase' of null
    at Object.inflector._apply_rules (/usr/local/share/npm/lib/node_modules/genem/node_modules/inflection/lib/inflection.js:173:48)
    at Object.inflector.pluralize (/usr/local/share/npm/lib/node_modules/genem/node_modules/inflection/lib/inflection.js:249:19)
    at controller (/usr/local/share/npm/lib/node_modules/genem/lib/genem.js:439:18)
    at Object.oncomplete (fs.js:297:15)
boilerplate > 
```

**Comment by sartymlg** [comment]
I have the same problem
