### ISSUE TITLE
Commander.js related issues?

### ISSUE THREAD

**Issue by irrg** [madhums/node-genem#5]
Would be fine with digging in and creating a patch, but was curious if you might know what's causing this?

```
/usr/local/lib/node_modules/genem/bin/genem:110
    program.confirm('destination is not empty, continue? ', function (ok) {
            ^
TypeError: Object #<Command> has no method 'confirm'
    at createModel (/usr/local/lib/node_modules/genem/bin/genem:110:13)
    at Command.file (/usr/local/lib/node_modules/genem/bin/genem:36:5)
    at Command.<anonymous> (/usr/local/lib/node_modules/genem/node_modules/commander/index.js:249:8)
    at Command.EventEmitter.emit (events.js:98:17)
    at Command.parseArgs (/usr/local/lib/node_modules/genem/node_modules/commander/index.js:477:12)
    at Command.parse (/usr/local/lib/node_modules/genem/node_modules/commander/index.js:370:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/genem/bin/genem:79:9)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

**Comment by madhums** [comment]
Yeah looks like an issue with commander. All the input related stuff were removed https://github.com/visionmedia/commander.js/pull/181 . https://github.com/visionmedia/co-prompt needs to be used instead
